version: '3'
services:
  postgres:
    image: postgres:14
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: junhyeok
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: findex_jun