version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: junhyeok
      POSTGRES_PASSWORD: 1234  # <- 여기에 비밀번호 입력
      POSTGRES_DB: findex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
