spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://shuttle.proxy.rlwy.net:55408/railway
    username: postgres
    password: paaLVKDCkjopiGOskumyTShEYYTxsDHS
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timezone: Asia/Seoul
    jackson:
      time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
