spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timezone: Asia/Seoul
    jackson:
      time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      postgresql: off
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    org.springframework.data.jpa.repository.query: off
    com.zaxxer.hikari: off
